### GET /transactions
GET http://localhost:8080/transactions/1 HTTP/1.1

###
### POST /transactions
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "stock": {
    "tick": "PETR4"
  },
  "quantity": 20,
  "unitaryValue": 30.9,
  "transactionType": "BUY",
  "transactionDate": "2023-10-29",
  "user":     {
    "id": 1
  }
}

###
### PUT /transactions
PUT http://localhost:8080/transactions/4 HTTP/1.1
Content-Type: application/json

{
  "stock": {
    "tick": "PETR4"
  },
  "quantity": 40,
  "unitaryValue": 30.9,
  "transactionType": "BUY",
  "transactionDate": "2023-10-29",
  "user":     {
    "id": 1
  }
}