### GET /users
GET http://localhost:8080/users HTTP/1.1


### GET /users/7
GET http://localhost:8080/users/7 HTTP/1.1

###


### POST /users
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json
Accept-Language: pt

{
  "name": "Marcio Sansone",
  "email": "marcio@email.com",
  "password":"123456",
  "role": "ADMIN",
  "actived": true
}


### DELETE /users/1
DELETE http://localhost:8080/users/4 HTTP/1.1


### POST /users/login
POST http://localhost:8080/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "marcio@email.com",
  "password": "123456"
}

### PUT /users/1
PUT http://localhost:8080/users/3 HTTP/1.1
Content-Type: application/json
Accept-Language: pt

{
    "name": "Maria Sansone",
    "email": "maria@email.com",
    "role": "USER",
    "actived": false
    
}
