### GET /users
GET http://localhost:8080/users HTTP/1.1

###


### POST /users
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
  "name": "Marcio Sansone",
  "email": "msansone@email.com",
  "password": "123456",
  "role": "ADMIN",
  "actived": true
}
